### ISSUE TITLE
Download links return 403 Forbidden HTTP Error

### ISSUE THREAD

**Issue by isaiahlg** [stephenjlee/oemaps-access-and-demand-data#1]
When using the download links in the CSV, it returns a 403 Forbidden Error. 
<img width="948" alt="image" src="https://github.com/stephenjlee/oemaps-access-and-demand-data/assets/40040369/d2e8f34e-da13-42f8-b97a-4e895ba60139">

Root cause seems to be the format of the link. The first one is a link that works, retrieved from the UI: https://www.openenergymaps.org/elec_demand
The second one is the one that returns the 403 error. 

1. Working: https://biospheric-vector.s3.amazonaws.com/open-energy-maps/2024Q1-downloads-2/20240326-2/SEN/435853_geoms.zip
2. Broken: https://biospheric-vector.s3.amazonaws.com/open-energy-maps/2024Q1-downloads/20240326/GHA/471928_geoms.geojson

Consider updated the format of the links in the download_links.csv, or updating the permissions for the existing URLs.

**Comment by stephenjlee** [comment]
Thank you for pointing this out! I just fixed the links.
